const KEY="balaji_crm_v1";
const USERS={admin:{password:"admin123",role:"Admin"},staff:{password:"staff123",role:"Staff"}};
let state=JSON.parse(localStorage.getItem(KEY)||'{"enquiries":[],"user":null}');
let page="dashboard", editingId=null;

function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function toast(msg){let t=document.querySelector(".toast");if(!t)return;t.textContent=msg;t.style.display="block";setTimeout(()=>t.style.display="none",1800)}
function render(){document.getElementById("app").innerHTML=state.user?appShell():login();bind()}
function login(){return `<div class="login"><div class="login-card"><div class="brand"><h1>Balaji Automobiles</h1><p>Showroom CRM</p></div><form id="loginForm"><div class="field"><label>Username</label><input id="username" required placeholder="admin or staff"></div><div class="field"><label>Password</label><input id="password" type="password" required placeholder="Password"></div><button class="primary" style="width:100%">Login</button><div id="loginErr" class="error">Invalid username or password.</div></form><p style="font-size:12px;color:#667085;margin-top:18px">Demo: admin / admin123 &nbsp; | &nbsp; staff / staff123</p></div></div>`}
function appShell(){return `<div class="layout"><aside class="sidebar"><div class="logo">Balaji Automobiles</div><div class="nav">
<button class="${page==="dashboard"?"active":""}" data-page="dashboard">📊 Dashboard</button>
<button class="${page==="enquiries"?"active":""}" data-page="enquiries">👥 Enquiries</button>
<button class="${page==="followups"?"active":""}" data-page="followups">📞 Follow-ups</button>
<button data-logout>🚪 Logout</button></div></aside><main class="main"><div class="top"><div><h2>${pageTitle()}</h2><div style="color:#667085;font-size:13px">Balaji Automobiles, Susner</div></div><div class="userbox"><span class="badge">${esc(state.user.role)}</span><b>${esc(state.user.username)}</b></div></div>${pageContent()}</main></div><div class="modal-back" id="modalBack"><div class="modal" id="modal"></div></div><div class="toast"></div>`}
function pageTitle(){return page==="dashboard"?"Dashboard":page==="enquiries"?"Customer Enquiries":"Follow-ups"}
function pageContent(){if(page==="dashboard")return dashboard();if(page==="enquiries")return enquiries();return followups()}
function dashboard(){let e=state.enquiries, todayN=e.filter(x=>x.enquiryDate===today()).length, due=e.filter(x=>x.followupDate&&x.followupDate<=today()&&x.status!=="Converted").length, conv=e.filter(x=>x.status==="Converted").length;return `<div class="cards"><div class="card"><div class="label">Total Enquiries</div><div class="num">${e.length}</div></div><div class="card"><div class="label">Today's Enquiries</div><div class="num">${todayN}</div></div><div class="card"><div class="label">Follow-ups Due</div><div class="num">${due}</div></div><div class="card"><div class="label">Converted</div><div class="num">${conv}</div></div></div><div class="panel"><div class="panel-head"><h3>Recent Enquiries</h3><button class="primary" data-add>+ New Enquiry</button></div>${miniTable(e.slice().sort((a,b)=>b.enquiryDate.localeCompare(a.enquiryDate)).slice(0,8))}</div>`}
function miniTable(rows){if(!rows.length)return `<div class="empty">No enquiries yet. Add your first customer enquiry.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Mobile</th><th>Vehicle</th><th>Finance</th><th>Status</th><th>Follow-up</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.model)}</td><td>${esc(x.payment)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.followupDate||"-")}</td></tr>`).join("")}</tbody></table></div>`}
function enquiries(){return `<div class="panel"><div class="panel-head"><h3>All Enquiries</h3><button class="primary" data-add>+ New Enquiry</button></div><div class="toolbar"><input id="search" placeholder="Search customer, mobile, village..." style="min-width:250px"><select id="statusFilter"><option value="">All Status</option><option>New</option><option>Follow-up</option><option>Interested</option><option>Converted</option><option>Lost</option></select><select id="payFilter"><option value="">Cash/Finance</option><option>Cash</option><option>Finance</option></select></div><div id="enquiryTable">${miniTable(state.enquiries)}</div></div>`}
function followups(){let rows=state.enquiries.filter(x=>x.followupDate&&x.status!=="Converted").sort((a,b)=>a.followupDate.localeCompare(b.followupDate));return `<div class="panel"><div class="panel-head"><h3>Pending Follow-ups</h3><button class="primary" data-add>+ New Enquiry</button></div>${miniFollow(rows)}</div>`}
function miniFollow(rows){if(!rows.length)return `<div class="empty">No pending follow-ups.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Follow-up</th><th>Customer</th><th>Mobile</th><th>Vehicle</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.followupDate)}</td><td>${esc(x.name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.model)}</td><td><span class="badge">${esc(x.status)}</span></td><td><button class="secondary" data-edit="${x.id}">Open</button></td></tr>`).join("")}</tbody></table></div>`}
function form(x={}){return `<form id="enquiryForm"><div class="grid2"><div class="field"><label>Customer Name *</label><input name="name" required value="${esc(x.name||"")}"></div><div class="field"><label>Mobile Number *</label><input name="mobile" required inputmode="numeric" value="${esc(x.mobile||"")}"></div><div class="field"><label>Village / City</label><input name="village" value="${esc(x.village||"")}"></div><div class="field"><label>Vehicle / Model</label><input name="model" placeholder="e.g. Splendor Plus" value="${esc(x.model||"")}"></div><div class="field"><label>Payment</label><select name="payment"><option ${x.payment==="Cash"?"selected":""}>Cash</option><option ${x.payment==="Finance"?"selected":""}>Finance</option></select></div><div class="field"><label>Exchange</label><select name="exchange"><option ${x.exchange==="No"||!x.exchange?"selected":""}>No</option><option ${x.exchange==="Yes"?"selected":""}>Yes</option></select></div><div class="field"><label>Enquiry Date</label><input type="date" name="enquiryDate" value="${esc(x.enquiryDate||today())}"></div><div class="field"><label>Follow-up Date</label><input type="date" name="followupDate" value="${esc(x.followupDate||"")}"></div><div class="field"><label>Status</label><select name="status">${["New","Follow-up","Interested","Converted","Lost"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Expected Delivery Date</label><input type="date" name="deliveryDate" value="${esc(x.deliveryDate||"")}"></div></div><div class="field"><label>Notes</label><textarea name="notes" rows="3">${esc(x.notes||"")}</textarea></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save Enquiry</button></div></form>`}
function openModal(x){editingId=x?.id||null;document.getElementById("modal").innerHTML=`<div class="panel-head"><h3>${editingId?"Edit Enquiry":"New Enquiry"}</h3><button class="secondary" data-close>✕</button></div>${form(x||{})}`;document.getElementById("modalBack").style.display="flex";document.getElementById("enquiryForm").onsubmit=saveEnquiry}
function saveEnquiry(ev){ev.preventDefault();let d=Object.fromEntries(new FormData(ev.target).entries());d.id=editingId||id();if(editingId)state.enquiries=state.enquiries.map(x=>x.id===editingId?d:x);else state.enquiries.push(d);save();document.getElementById("modalBack").style.display="none";toast(editingId?"Enquiry updated":"Enquiry saved");render()}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector("[data-logout]")?.addEventListener("click",()=>{state.user=null;save();render()});document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openModal());document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openModal(state.enquiries.find(x=>x.id===b.dataset.edit)));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>document.getElementById("modalBack").style.display="none");let lf=document.getElementById("loginForm");if(lf)lf.onsubmit=e=>{e.preventDefault();let u=document.getElementById("username").value.trim(),p=document.getElementById("password").value;if(USERS[u]?.password===p){state.user={username:u,role:USERS[u].role};save();page="dashboard";render()}else document.getElementById("loginErr").style.display="block"};let s=document.getElementById("search");if(s){let f=()=>{let q=s.value.toLowerCase(),st=document.getElementById("statusFilter").value,p=document.getElementById("payFilter").value;let rows=state.enquiries.filter(x=>(!q||[x.name,x.mobile,x.village,x.model].join(" ").toLowerCase().includes(q))&&(!st||x.status===st)&&(!p||x.payment===p));document.getElementById("enquiryTable").innerHTML=miniTable(rows)};s.oninput=f;document.getElementById("statusFilter").onchange=f;document.getElementById("payFilter").onchange=f}}
render();