const sb=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
let user=null,profile=null,page="dashboard",editingId=null,enquiries=[];

const $=s=>document.querySelector(s), today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function toast(m){const t=$(".toast");if(!t)return;t.textContent=m;t.style.display="block";setTimeout(()=>t.style.display="none",1800)}
function configured(){return window.SUPABASE_URL && !window.SUPABASE_URL.includes("PASTE_") && window.SUPABASE_ANON_KEY && !window.SUPABASE_ANON_KEY.includes("PASTE_")}
function render(){document.getElementById("app").innerHTML=user?shell():login();bind()}
function login(){return `<div class="login"><div class="login-card"><div class="brand"><h1>Balaji Automobiles</h1><p>Cloud CRM</p></div>${!configured()?`<div class="error" style="display:block">Supabase is not connected yet. Fill in config.js first.</div>`:`<form id="authForm"><div class="field"><label>Email</label><input id="email" type="email" required></div><div class="field"><label>Password</label><input id="password" type="password" minlength="6" required></div><div class="field" id="nameField" style="display:none"><label>Full name</label><input id="fullName"></div><button class="primary" style="width:100%" id="authBtn">Login</button><div id="authErr" class="error"></div><button type="button" class="switch" id="toggleAuth">Create staff account</button></form>`}</div></div>`}
function shell(){return `<div class="layout"><aside class="sidebar"><div class="logo">Balaji Automobiles</div><div class="nav"><button class="${page==="dashboard"?"active":""}" data-page="dashboard">📊 Dashboard</button><button class="${page==="enquiries"?"active":""}" data-page="enquiries">👥 Enquiries</button><button class="${page==="followups"?"active":""}" data-page="followups">📞 Follow-ups</button><button data-logout>🚪 Logout</button></div></aside><main class="main"><div class="top"><div><h2>${page==="dashboard"?"Dashboard":page==="enquiries"?"Customer Enquiries":"Follow-ups"}</h2><div style="color:#667085;font-size:13px">Balaji Automobiles, Susner</div></div><div class="userbox"><span class="badge">${esc(profile?.role||"staff")}</span><b>${esc(user.email)}</b></div></div>${content()}</main></div><div class="modal-back" id="modalBack"><div class="modal" id="modal"></div></div><div class="toast"></div>`}
function content(){if(page==="dashboard")return dashboard();if(page==="enquiries")return enquiriesPage();return followups()}
function dashboard(){let t=enquiries.filter(x=>x.enquiry_date===today()).length,d=enquiries.filter(x=>x.followup_date&&x.followup_date<=today()&&x.status!=="Converted").length,c=enquiries.filter(x=>x.status==="Converted").length;return `<div class="cards"><div class="card"><div class="label">Total Enquiries</div><div class="num">${enquiries.length}</div></div><div class="card"><div class="label">Today's Enquiries</div><div class="num">${t}</div></div><div class="card"><div class="label">Follow-ups Due</div><div class="num">${d}</div></div><div class="card"><div class="label">Converted</div><div class="num">${c}</div></div></div><div class="panel"><div class="panel-head"><h3>Recent Enquiries</h3><button class="primary" data-add>+ New Enquiry</button></div>${table(enquiries.slice(0,8))}</div>`}
function table(rows){if(!rows.length)return `<div class="empty">No enquiries found.</div>`;return `<div class="table-wrap"><table><thead><tr><th>Customer</th><th>Mobile</th><th>Village</th><th>Vehicle</th><th>Payment</th><th>Status</th><th>Follow-up</th><th>Action</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.customer_name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.village)}</td><td>${esc(x.model)}</td><td>${esc(x.payment)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.followup_date||"-")}</td><td><button class="secondary" data-edit="${x.id}">Edit</button></td></tr>`).join("")}</tbody></table></div>`}
function enquiriesPage(){return `<div class="panel"><div class="panel-head"><h3>All Enquiries</h3><button class="primary" data-add>+ New Enquiry</button></div><div class="toolbar"><input id="search" placeholder="Search customer, mobile, village, model..." style="min-width:260px"><select id="statusFilter"><option value="">All Status</option>${["New","Follow-up","Interested","Converted","Lost"].map(x=>`<option>${x}</option>`).join("")}</select><select id="payFilter"><option value="">Cash/Finance</option><option>Cash</option><option>Finance</option></select></div><div id="enquiryTable">${table(enquiries)}</div></div>`}
function followups(){let r=enquiries.filter(x=>x.followup_date&&x.status!=="Converted").sort((a,b)=>a.followup_date.localeCompare(b.followup_date));return `<div class="panel"><div class="panel-head"><h3>Pending Follow-ups</h3><button class="primary" data-add>+ New Enquiry</button></div>${table(r)}</div>`}
function form(x={}){return `<form id="enquiryForm"><div class="grid2"><div class="field"><label>Customer Name *</label><input name="customer_name" required value="${esc(x.customer_name)}"></div><div class="field"><label>Mobile Number *</label><input name="mobile" required inputmode="numeric" value="${esc(x.mobile)}"></div><div class="field"><label>Village / City</label><input name="village" value="${esc(x.village)}"></div><div class="field"><label>Vehicle / Model</label><input name="model" value="${esc(x.model)}"></div><div class="field"><label>Payment</label><select name="payment"><option ${x.payment==="Cash"||!x.payment?"selected":""}>Cash</option><option ${x.payment==="Finance"?"selected":""}>Finance</option></select></div><div class="field"><label>Exchange</label><select name="exchange"><option ${x.exchange==="No"||!x.exchange?"selected":""}>No</option><option ${x.exchange==="Yes"?"selected":""}>Yes</option></select></div><div class="field"><label>Enquiry Date</label><input type="date" name="enquiry_date" value="${esc(x.enquiry_date||today())}"></div><div class="field"><label>Follow-up Date</label><input type="date" name="followup_date" value="${esc(x.followup_date||"")}"></div><div class="field"><label>Status</label><select name="status">${["New","Follow-up","Interested","Converted","Lost"].map(s=>`<option ${x.status===s?"selected":""}>${s}</option>`).join("")}</select></div><div class="field"><label>Expected Delivery Date</label><input type="date" name="delivery_date" value="${esc(x.delivery_date||"")}"></div></div><div class="field"><label>Notes</label><textarea name="notes" rows="3">${esc(x.notes)}</textarea></div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save Enquiry</button></div></form>`}
function openModal(x={}){editingId=x.id||null;$("#modal").innerHTML=`<div class="panel-head"><h3>${editingId?"Edit Enquiry":"New Enquiry"}</h3><button class="secondary" data-close>✕</button></div>${form(x)}`;$("#modalBack").style.display="flex";$("#enquiryForm").onsubmit=saveEnquiry}
async function saveEnquiry(e){e.preventDefault();let d=Object.fromEntries(new FormData(e.target).entries());d.created_by=user.id;if(editingId){let {error}=await sb.from("enquiries").update(d).eq("id",editingId);if(error)return alert(error.message);toast("Enquiry updated")}else{let {error}=await sb.from("enquiries").insert(d);if(error)return alert(error.message);toast("Enquiry saved")}$("#modalBack").style.display="none";await load();render()}
async function load(){let {data,error}=await sb.from("enquiries").select("*").order("created_at",{ascending:false});if(error){console.error(error);return}enquiries=data||[]}
async function init(){if(!configured()){render();return}const {data}=await sb.auth.getSession();user=data.session?.user||null;if(user){let r=await sb.from("profiles").select("*").eq("id",user.id).single();profile=r.data}if(user)await load();render();sb.auth.onAuthStateChange(async(_e,s)=>{user=s?.user||null;if(user){let r=await sb.from("profiles").select("*").eq("id",user.id).single();profile=r.data;await load()}else profile=null;render()})}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=async()=>{page=b.dataset.page;await load();render()});document.querySelector("[data-logout]")?.addEventListener("click",()=>sb.auth.signOut());document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>openModal());document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openModal(enquiries.find(x=>x.id===b.dataset.edit)));document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$("#modalBack").style.display="none");let f=$("#search");if(f){let filter=()=>{let q=f.value.toLowerCase(),s=$("#statusFilter").value,p=$("#payFilter").value;$("#enquiryTable").innerHTML=table(enquiries.filter(x=>(!q||[x.customer_name,x.mobile,x.village,x.model].join(" ").toLowerCase().includes(q))&&(!s||x.status===s)&&(!p||x.payment===p)))};f.oninput=filter;$("#statusFilter").onchange=filter;$("#payFilter").onchange=filter}let af=$("#authForm");if(af){let signup=false;$("#toggleAuth").onclick=()=>{signup=!signup;$("#nameField").style.display=signup?"block":"none";$("#authBtn").textContent=signup?"Create account":"Login";$("#toggleAuth").textContent=signup?"Back to login":"Create staff account";$("#authErr").style.display="none"};af.onsubmit=async e=>{e.preventDefault();$("#authErr").style.display="none";let email=$("#email").value.trim(),password=$("#password").value;if(signup){let {error}=await sb.auth.signUp({email,password,options:{data:{full_name:$("#fullName").value.trim()}}});if(error){$("#authErr").textContent=error.message;$("#authErr").style.display="block"}else alert("Account created. If email confirmation is enabled, confirm the email, then log in.")}else{let {error}=await sb.auth.signInWithPassword({email,password});if(error){$("#authErr").textContent=error.message;$("#authErr").style.display="block"}}}}}
init();